name: Demo
on:
  push:
    branches: [ master ]

jobs:
  demo:
    name: Demo
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: lukka/run-vcpkg@v4
      #   id: runvcpkg
      #   with:
      #     vcpkgArguments: pcre2
      #     vcpkgGitCommitId: 6185aa76504a5025f36754324abf307cc776f3da
      #     vcpkgDirectory: ${{ github.workspace }}/vcpkg/
      #     vcpkgTriplet: x64-windows-static          
          
      - uses: lukka/run-cmake@v3
        with:
          buildDirectory: ${{ github.workspace }}/build
          buildWithCMakeArgs: '-G Ninja'
          # cmakeAppendedArgs: ''
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
          # vcpkgTriplet: x64-windows-static
          # useVcpkgToolchainFile: true
          
